from __future__ import annotations


DEMO_ITEMS = [
    {
        "image_url": "/static/placeholders/linen_shirt.svg",
        "category": "上衣",
        "material": "亚麻",
        "color": "米白色",
        "style": "极简",
        "tags": ["长袖", "透气", "夏季", "衬衫"],
    },
    {
        "image_url": "/static/placeholders/navy_trouser.svg",
        "category": "裤装",
        "material": "羊毛",
        "color": "藏青色",
        "style": "通勤",
        "tags": ["利落", "垂坠"],
    },
    {
        "image_url": "/static/placeholders/silk_skirt.svg",
        "category": "裙装",
        "material": "真丝",
        "color": "浅蓝色",
        "style": "优雅",
        "tags": ["半裙", "垂坠", "约会"],
    },
    {
        "image_url": "/static/placeholders/cotton_tee.svg",
        "category": "上衣",
        "material": "纯棉",
        "color": "白色",
        "style": "休闲",
        "tags": ["T恤", "亲肤", "日常"],
    },
    {
        "image_url": "/static/placeholders/sneaker.svg",
        "category": "鞋子",
        "material": "织物",
        "color": "白色",
        "style": "运动",
        "tags": ["运动鞋", "舒适"],
    },
    {
        "image_url": "/static/placeholders/loafer.svg",
        "category": "鞋子",
        "material": "皮质",
        "color": "棕色",
        "style": "通勤",
        "tags": ["乐福鞋", "舒适"],
    },
    {
        "image_url": "/static/placeholders/tote.svg",
        "category": "包包",
        "material": "帆布",
        "color": "米白色",
        "style": "通勤",
        "tags": ["托特包", "可装电脑", "容量适中"],
    },
    {
        "image_url": "/static/placeholders/crossbody.svg",
        "category": "包包",
        "material": "皮质",
        "color": "黑色",
        "style": "极简",
        "tags": ["小挎包", "少量物品"],
    },
    {
        "image_url": "/static/placeholders/sunglasses.svg",
        "category": "配饰",
        "material": "树脂",
        "color": "黑色",
        "style": "极简",
        "tags": ["墨镜", "防晒"],
    },
    {
        "image_url": "/static/placeholders/light_jacket.svg",
        "category": "外套",
        "material": "纯棉",
        "color": "浅蓝色",
        "style": "休闲",
        "tags": ["长袖", "防晒", "可叠穿"],
    },
]
